CREATE TABLE IF NOT EXISTS `__record_change_elements` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TABLE` int(11) DEFAULT NULL,
  `ID_ELEMENT` int(11) DEFAULT NULL,
  `CHANGE` varchar(8000) DEFAULT NULL,
  `DATE_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;